#!/bin/bash
#MAINTAINER: Hossein Yousefi <yousefi.hosein.o@gmail.com>


echo "############ Welcome to SSC ############"
echo
echo "For help: ssc help"
echo

INPUT=$1
SSC_CONF=$HOME/.ssc.conf

Config-check () {
if [[ ! -f ${SSC_CONF} ]]
then
	echo "Configuration file is missed \"${SSC_CONF}\" or you didn't add a node yet."
	echo "Please add your first node with -a."
	echo
	exit
fi

}

# Sort config file
if [[ -f ${SSC_CONF} ]]
then
	sed -n '1,6'p ${SSC_CONF} > x01
	sed -n '7,$'p ${SSC_CONF}|sort -t , -k 7 >> x01
	mv x01 ${SSC_CONF}
fi

Add-node () {

echo "# Please answer next questions: "
read -p "Hostname or IP address: " "SSC_Host"

while [[ -z ${SSC_Host} ]]
do
        read -p "Hostname or IP address: " "SSC_Host"
done

read -p "Username(default is root): " "SSC_Username"
read -p "Port number(default is 22): " "SSC_Port"
read -p "Options for ssh(default is null): " "SSC_Options"
read -p "Private key(default is null): " "SSC_Key"
read -p "Which group does it belong to(default is General): " "SSC_Group"
read -p "connection name(UNIQUE): " "SSC_Name"

while [[ ${#SSC_Name} == 0 ]] || [[ $(awk -F "," '{print $1}' ${SSC_CONF} |grep -w ${SSC_Name}) ]]
do
        read -p "## This name is already taken, choose another one: " "SSC_Name"
done &>/dev/null

SSC_Username=$(echo ${SSC_Username}|sed 's/ /-/')
SSC_Port=$(echo ${SSC_Port}|sed 's/ /-/')
SSC_Options=$(echo ${SSC_Options}|sed 's/ /-/')
SSC_Key=$(echo ${SSC_Key}|sed 's/ /-/')
SSC_Group=$(echo ${SSC_Group}|sed 's/ /-/')
SSC_Name=$(echo ${SSC_Name}|sed 's/ /-/')

if [[ -f ${SSC_CONF} ]]
then
        echo "${SSC_Name},${SSC_Host},${SSC_Username:-root},${SSC_Port:-22},${SSC_Options:-null},${SSC_Key:-null},${SSC_Group:-General}" >> ${SSC_CONF}
else
        echo "#MAINTAINER: Hossein Yousefi <yousefi.hosein.o@gmail.com>" > ${SSC_CONF}

        echo "#THIS IS SSC CONFIGURATION FILE AND SHOULD NOT BE EDITTED MANUALLY, IN CASE YOU DON'T KNOW ABOUT THE ARCHITECTURE." >> ${SSC_CONF}

        echo >> ${SSC_CONF}

        echo "## NAME, HOST, USERNAME, PORT, OPTIONS, PRIVATE_KEY, GROUP" >> ${SSC_CONF}

        echo >> ${SSC_CONF}

        echo >> ${SSC_CONF}

        echo "${SSC_Name},${SSC_Host},${SSC_Username:-root},${SSC_Port:-22},${SSC_Options:-null},${SSC_Key:-null},${SSC_Group:-General}" >> ${SSC_CONF}
fi

echo
echo "# Your node has been added successfuly."
}

List-node () {

Config-check

SSC_ALL_GROUPS=$(cat ${SSC_CONF} |grep -v "^#"|grep -v ^$| sed 's/,/ /g'| sort -k 7 |awk '{print $NF}'|uniq -d)

SSC_ALL_GROUPS="${SSC_ALL_GROUPS} $(cat ${SSC_CONF} |grep -v "^#"|grep -v ^$| sed 's/,/ /g'| sort -k 7 |awk '{print $NF}'|uniq -u)"

SSC_ALL_GROUPS="$(echo ${SSC_ALL_GROUPS} |tr " " "\n"| sort -d| xargs)"

echo

printf "%-19s %-25s %-16s %-10s %-10s %-10s %-13s\n\n" Name Host UserName Port Options SshKey

for GROUP_NAME in $SSC_ALL_GROUPS
do
    echo
    printf "\e[0;31m%-5s\e[m \e[0;31m%-5s\e[m %-20s %-5s %-10s\n" "________________" ${GROUP_NAME}
    echo
    for SEPERATE_GROUP in $(grep -w $GROUP_NAME ${SSC_CONF})
    do

        SSC_Name=$(echo $SEPERATE_GROUP |awk -F "," '{print $1}')
        SSC_Host=$(echo $SEPERATE_GROUP |awk -F "," '{print $2}')
        SSC_Username=$(echo $SEPERATE_GROUP |awk -F "," '{print $3}')
        SSC_Port=$(echo $SEPERATE_GROUP |awk -F "," '{print $4}')
        SSC_Options=$(echo $SEPERATE_GROUP |awk -F "," '{print $5}')
	if [[ $SSC_Options != null ]]
	then
		SSC_Options=True
	fi
        SSC_Key=$(echo $SEPERATE_GROUP |awk -F "," '{print $6}')
	if [[ $SSC_Key != null ]]
        then
                SSC_Key=True
        fi

        printf "%-16s %-30s %-15s %-10s %-10s %-10s  %-13s\n" ${SSC_Name} ${SSC_Host} ${SSC_Username} ${SSC_Port} ${SSC_Options} ${SSC_Key}
    done
done

echo

}

print_menu() {

Config-check

local SSC_function_arguments=($@)

local SSC_selected_item="$1"
local SSC_menu_items=(${SSC_function_arguments[@]:1})
local SSC_menu_size="${#SSC_menu_items[@]}"

printf "%-19s %-25s %-16s %-10s %-10s %-13s %-13s\n\n" Name Host UserName Port Options SshKey Group

for (( i = 0; i < $SSC_menu_size; ++i ))
do

    if [ "$i" = "$SSC_selected_item" ]
    then
		echo 

		SSC_LINE=$(sed '1,6 d' $SSC_CONF| grep "^${SSC_menu_items[i]},")

		SSC_Name=$(echo $SSC_LINE |awk -F "," '{print $1}')
		SSC_Host=$(echo $SSC_LINE |awk -F "," '{print $2}')
		SSC_Username=$(echo $SSC_LINE |awk -F "," '{print $3}')
		SSC_Port=$(echo $SSC_LINE |awk -F "," '{print $4}')
	        SSC_Options=$(echo $SSC_LINE |awk -F "," '{print $5}')
        	if [[ $SSC_Options != null ]]
	        then
        	        SSC_Options=True
	        fi
	        SSC_Key=$(echo $SSC_LINE |awk -F "," '{print $6}')
	        if [[ $SSC_Key != null ]]
	        then
	                SSC_Key=True
	        fi		
		SSC_Group=$(echo $SSC_LINE |awk -F "," '{print $7}')

		echo -e "\e[1;45m $(printf "%-16s %-30s %-15s %-10s %-10s %-10s  %-13s\n" ${SSC_Name} ${SSC_Host} ${SSC_Username} ${SSC_Port} ${SSC_Options} ${SSC_Key} ${SSC_Group})  \e[0m"
    else
        echo

        SSC_LINE=$(sed '1,6 d' $SSC_CONF| grep "^${SSC_menu_items[i]},")

        SSC_Name=$(echo $SSC_LINE |awk -F "," '{print $1}')
        SSC_Host=$(echo $SSC_LINE |awk -F "," '{print $2}')
        SSC_Username=$(echo $SSC_LINE |awk -F "," '{print $3}')
        SSC_Port=$(echo $SSC_LINE |awk -F "," '{print $4}')
        SSC_Options=$(echo $SSC_LINE |awk -F "," '{print $5}')
        if [[ $SSC_Options != null ]]
        then
                SSC_Options=True
        fi
        SSC_Key=$(echo $SSC_LINE |awk -F "," '{print $6}')
        if [[ $SSC_Key != null ]]
        then
                SSC_Key=True
        fi	
        SSC_Group=$(echo $SSC_LINE |awk -F "," '{print $7}')

        printf "%-16s %-30s %-15s %-10s %-10s %-10s  %-13s\n" ${SSC_Name} ${SSC_Host} ${SSC_Username} ${SSC_Port} ${SSC_Options} ${SSC_Key} ${SSC_Group}
        fi
done
}

run_menu()  {

Config-check

local SSC_function_arguments=($@)

local SSC_selected_item="$1"
local SSC_menu_items=(${SSC_function_arguments[@]:1})
local SSC_menu_size="${#SSC_menu_items[@]}"
local SSC_menu_limit=$((SSC_menu_size - 1))

clear
print_menu "$SSC_selected_item" "${SSC_menu_items[@]}"

while read -rsn1 input
do
    case "$input"
    in
        $'\x1B')
            read -rsn1 -t 0.1 input
            if [ "$input" = "[" ]
            then
                read -rsn1 -t 0.1 input
                case "$input"
                in
                    A)
                        if [ "$SSC_selected_item" -ge 1 ]
                        then
                            SSC_selected_item=$((SSC_selected_item - 1))
                            clear
                            print_menu "$SSC_selected_item" "${SSC_menu_items[@]}"
                        fi
                        ;;
                    B)
                        if [ "$SSC_selected_item" -lt "$SSC_menu_limit" ]
                        then
                            SSC_selected_item=$((SSC_selected_item + 1))
                            clear
                            print_menu "$SSC_selected_item" "${SSC_menu_items[@]}"
                        fi
                        ;;
                esac
            fi
            read -rsn5 -t 0.1
            ;;
        "")  
            return "$SSC_selected_item"
            ;;
    esac
done
}

select_menu() {

Config-check

SSC_selected_item=0
SSC_menu_items=($(cat $SSC_CONF |grep -v "^#"|grep -v ^$| sed 's/,/ /g'|awk '{print $1}'))

run_menu "$SSC_selected_item" "${SSC_menu_items[@]}"
SSC_menu_result="$?"

echo

case "$SSC_menu_result"
in
        *)
                SSC_SELECTED_LINE=$(expr ${SSC_menu_result} + 7)
                Connect-node $(sed "${SSC_SELECTED_LINE}q;d" $SSC_CONF|awk -F "," '{print $1}')
                ;;
esac
}

Delete-node () {

Config-check

read -p "Give the name of the node that you want to delete: " "SSC_Node_Name"

SSC_LINE_NUMBER=$(grep -n ^${SSC_Node_Name}, ${SSC_CONF} |awk -F ":" '{print $1}')

if [[ ! -z $SSC_LINE_NUMBER  ]]
then
        sed -i "${SSC_LINE_NUMBER} d" ${SSC_CONF}
        echo "# Your node has been deleted successfuly."
else
        echo
        echo "# Your node "${SSC_Node_Name}" doesn't exist."
fi

}

Copy-key () {

Config-check

List-node

read -p "Which node do you like to copy your key? " "SSC_Node_Name"


SSC_LINE_NUMBER=$(grep -n ^${SSC_Node_Name}, ${SSC_CONF} |awk -F ":" '{print $1}')

if [[ ! -z $SSC_LINE_NUMBER  ]]
then
        SSC_Key=$(grep -w ^${SSC_Node_Name} ${SSC_CONF} |awk -F "," '{print $6}')
        if [[ $SSC_Key == null ]]
        then
                SSC_Key="${HOME}/.ssh/id_rsa"
                echo "# The key is ${SSC_Key}"
        else
                echo "# The key is ${SSC_Key}"
        fi

        SSC_Username=$(grep -w ^${SSC_Node_Name} ${SSC_CONF} |awk -F "," '{print $3}')
        SSC_Host=$(grep -w ^${SSC_Node_Name} ${SSC_CONF} |awk -F "," '{print $2}')
        SSC_Port=$(grep -w ^${SSC_Node_Name} ${SSC_CONF} |awk -F "," '{print $4}')

        echo
        ssh-copy-id -p ${SSC_Port} -i ${SSC_Key} ${SSC_Username}@${SSC_Host} && echo "# Your key has been added to '${SSC_Host}'"
else
        echo
        echo "# Your node "${SSC_Node_Name}" doesn't exist."
fi

}

Backup () {

Config-check

read -p "Do you want to take a backup?(y/n) " "SSC_BACKUP"

if [[ ${SSC_BACKUP} == y ]]
then
        cp ${SSC_CONF} $(date '+%d-%m-%y-%H-%M')-ssc.conf && gzip $(date '+%d-%m-%y-%H-%M')-ssc.conf  && echo "Find your backup here: ${PWD}/$(date '+%d-%m-%y-%H-%M')-ssc.conf.gz"
fi
}

Restore () {

read -p "Do you want to restore your backup?(y/n) " "SSC_RESTORE"

if [[ ${SSC_RESTORE} == y ]]
then
        read -p "Please write the absolute path to your backup(.gz): " "SSC_RESTORE_PATH"
        gzip -d ${SSC_RESTORE_PATH} -c > ${SSC_CONF} && echo "Backup is restored successfuly."
fi

}

Connect-node () {

Config-check

SSC_Node_Name=$1

SSC_LINE_NUMBER=$(grep -n ^${SSC_Node_Name}, ${SSC_CONF} |awk -F ":" '{print $1}')

if [[ ! -z $SSC_LINE_NUMBER  ]]
then
        SSC_Key=$(grep -w ^${SSC_Node_Name} ${SSC_CONF} |awk -F "," '{print $6}')
        if [[ $SSC_Key == null ]]
        then
                SSC_Key="${HOME}/.ssh/id_rsa"
                echo "# The key is ${SSC_Key}"
        else
                echo "# The key is ${SSC_Key}"
        fi

        SSC_Username=$(grep -w ^${SSC_Node_Name} ${SSC_CONF} |awk -F "," '{print $3}')
        SSC_Host=$(grep -w ^${SSC_Node_Name} ${SSC_CONF} |awk -F "," '{print $2}')
        SSC_Port=$(grep -w ^${SSC_Node_Name} ${SSC_CONF} |awk -F "," '{print $4}')
        SSC_Options=$(grep -w ^${SSC_Node_Name} ${SSC_CONF} |awk -F "," '{print $5}')

        if [[ ${SSC_Options} == null ]]
        then
                SSC_Options=
	else
		SSC_OPTION_COMMAND=-o
        fi

        echo
		echo "Connecting to ${SSC_Node_Name}..."
		ssh -p ${SSC_Port} -i ${SSC_Key}  ${SSC_Username}@${SSC_Host} ${SSC_OPTION_COMMAND} ${SSC_Options}
else
        echo
        echo "# Your node "${SSC_Node_Name}" doesn't exist."
fi

}

helps () {

echo """

This is a ssh connection manager tool.

OPTIONS:

-a                      To add a node

-l                      List nodes

-d                      Delete node

-k                      Copy key to node

-b                      Configuration's backup

-r                      Restore backup

-h, help       		This page

-c <NODE_NAME>          Connect to the NODE

_________________________________________________________________
SAMPLE:

ssm -a         			TO add a new node

ssm -c azure-server		connect to "azure-server"         

"""
}



case $INPUT in

        -a)
            Add-node
        ;;

        -l)
            List-node
        ;;

        -d)
            Delete-node
        ;;

        -k)
            Copy-key
        ;;

        -b)
            Backup
        ;;

        -r)
            Restore
        ;;

        -c)
            Connect-node $2
        ;;

        -h|help)
            helps
        ;;
		*)
			if [[ $(cat ${SSC_CONF} |awk -F "," '{print $1}'|grep $INPUT) ]]
			then
				Connect-node $INPUT
			else
				select_menu
			fi
		;;

esac
